# https://pre-commit.com/
# https://github.com/pre-commit/pre-commit-hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v6.0.0
    hooks:
      - id:    check-yaml                             # https://github.com/pre-commit/pre-commit-hooks#check-yaml
        files: \.ya?ml$
  - repo: https://github.com/golangci/golangci-lint   # https://github.com/golangci/golangci-lint/blob/main/.pre-commit-hooks.yaml
    rev:  v2.13.1
    hooks:
      - id:             golangci-lint
        name:           golangci-lint
        entry:          golangci-lint
        language:       system
        types:          [go]
        pass_filenames: false
        args:           [run, --verbose, gogpu/...]  # requires a go.work file where the last line is "use ./gogpu"
  - repo: local
    hooks:
      - id:             go-test
        name:           go test
        entry:          go test -v -race ./gogpu/...
        files:          \.go$|^go\.(?:mod|sum)$
        language:       system
        pass_filenames: false
        require_serial: true
